name: msquare_market
description: MSQUARE MARKET

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.3+6
#

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
##
##
  flutter:
    sdk: flutter
##
## Front end
  adaptive_dialog: ^1.8.0+1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  flutter_image_slideshow: ^0.1.4
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  connectivity_plus: ^3.0.2
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  timezone: ^0.9.2
  camera: ^0.10.5
  pie_chart: ^5.3.2
  flutter_datetime_picker: ^1.5.1
  sticky_headers: ^0.3.0+2

##
## Authentication and Backend
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  flutter_facebook_auth: ^4.4.1+1
  google_sign_in: ^5.3.3
  firebase_dynamic_links: ^5.0.7
  sign_in_with_apple: ^4.2.0
  firebase_crashlytics: ^3.0.7

##
##  State Management Dependency Injection

  get: ^4.6.5
  get_it: ^7.2.0
  provider: ^6.0.4
## Fonts
##
  google_fonts: ^3.0.1

##
## Backend and Feature helpers
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  local_auth: ^2.1.1
  modal_progress_hud_nsn: ^0.2.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.6
  email_validator: ^2.1.16
  webview_flutter: ^3.0.4
  tutorial_coach_mark: ^1.2.4
  socket_io_client: ^2.0.2



##
## These dependencies do not get compiled into app source code, 
## They are only used as helpers during development purposes
##
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

# This is used to for automated app_icons generation
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/app_icons/app_icon.png"
  # android: true
  ios: true
  remove_alpha_ios: true
  # /assets/app_icons/app_icon.png

# flutter:
flutter:
  uses-material-design: true
  # fonts:
  #   - family: Noto Sans
  #     fonts:
  #       - asset: fonts/Noto_Sans/NotoSans-Regular.ttf
  #       - asset: fonts/Noto_Sans/NotoSans-Italic.ttf
  #         style: italic
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins/Poppins-Regular.ttf
  #       - asset: fonts/Poppins/Poppins-Italic.ttf
  #         style: italic
  assets:
    - assets/
    - assets/v2/
    - assets/banners/
    - assets/app_icons/
    - assets/social_icons/
    - assets/notification_icons/
    - assets/svg_icons/
    - assets/my_icons/
    - assets/flags/
    - assets/exchange/
    - assets/super_save/
    - assets/super_save/banks/
    - assets/super_save/html/
